apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: marver-cronjob
spec:
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - env:
            - name: TOKEN
              valueFrom:
                secretKeyRef:
                  key: token
                  name: discord
            - name: WEBHOOK_ID
              valueFrom:
                secretKeyRef:
                  key: id
                  name: discord-autoscale-webhook
            - name: WEBHOOK_TOKEN
              valueFrom:
                secretKeyRef:
                  key: token
                  name: discord-autoscale-webhook
            - name: NAMESPACE
              value: default
            - name: STATEFULSET
              value: my-discord-bot
            - name: CONTAINER_NAME
              value: my-container-name
            - name: COUNT_ENV_VAR
              value: SHARD_COUNT
            image: quay.io/kelwing/marver
            imagePullPolicy: IfNotPresent
            name: marver
            resources: {}
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
          dnsPolicy: ClusterFirst
          restartPolicy: Never
          schedulerName: default-scheduler
          securityContext: {}
          terminationGracePeriodSeconds: 30
          serviceAccountName: marver-access
  schedule: 30 * * * *
  successfulJobsHistoryLimit: 3
  suspend: false
